export enum ReadingHumanStatus {
  OPEN = 'OPEN',
  IN_PROGRESS = 'IN_PROGRESS',
  DONE = 'DONE',
}

export const TAROT_CARD_LIST = [
  { id: 'MAJOR_O_THE_FOOL', name: '愚者' },
  { id: 'MAJOR_I_THE_MAGICIAN', name: '魔術師' },
  { id: 'MAJOR_II_THE_HIGH_PRIESTESS', name: '女祭司' },
  { id: 'MAJOR_III_THE_EMPRESS', name: '皇后' },
  { id: 'MAJOR_IV_THE_EMPEROR', name: '皇帝' },
  { id: 'MAJOR_V_THE_HIEROPHANT', name: '教皇' },
  { id: 'MAJOR_VI_THE_LOVERS', name: '戀人' },
  { id: 'MAJOR_VII_THE_CHARIOT', name: '戰車' },
  { id: 'MAJOR_VIII_STRENGTH', name: '力量' },
  { id: 'MAJOR_IX_THE_HERMIT', name: '隱者' },
  { id: 'MAJOR_X_WHEEL_OF_FORTUNE', name: '命運之輪' },
  { id: 'MAJOR_XI_JUSTICE', name: '正義' },
  { id: 'MAJOR_XII_THE_HANGED_MAN', name: '倒吊人' },
  { id: 'MAJOR_XIII_DEATH', name: '死神' },
  { id: 'MAJOR_XIV_TEMPERANCE', name: '節制' },
  { id: 'MAJOR_XV_THE_DEVIL', name: '惡魔' },
  { id: 'MAJOR_XVI_THE_TOWER', name: '高塔' },
  { id: 'MAJOR_XVII_THE_STAR', name: '星星' },
  { id: 'MAJOR_XVIII_THE_MOON', name: '月亮' },
  { id: 'MAJOR_XIX_THE_SUN', name: '太陽' },
  { id: 'MAJOR_XX_JUDGEMENT', name: '審判' },
  { id: 'MAJOR_XXI_THE_WORLD', name: '世界' },

  { id: 'WANDS_ACE', name: '權杖王牌' },
  { id: 'WANDS_TWO', name: '權杖二' },
  { id: 'WANDS_THREE', name: '權杖三' },
  { id: 'WANDS_FOUR', name: '權杖四' },
  { id: 'WANDS_FIVE', name: '權杖五' },
  { id: 'WANDS_SIX', name: '權杖六' },
  { id: 'WANDS_SEVEN', name: '權杖七' },
  { id: 'WANDS_EIGHT', name: '權杖八' },
  { id: 'WANDS_NINE', name: '權杖九' },
  { id: 'WANDS_TEN', name: '權杖十' },
  { id: 'WANDS_PAGE', name: '權杖侍者' },
  { id: 'WANDS_KNIGHT', name: '權杖騎士' },
  { id: 'WANDS_QUEEN', name: '權杖皇后' },
  { id: 'WANDS_KING', name: '權杖國王' },

  { id: 'CUPS_ACE', name: '聖杯王牌' },
  { id: 'CUPS_TWO', name: '聖杯二' },
  { id: 'CUPS_THREE', name: '聖杯三' },
  { id: 'CUPS_FOUR', name: '聖杯四' },
  { id: 'CUPS_FIVE', name: '聖杯五' },
  { id: 'CUPS_SIX', name: '聖杯六' },
  { id: 'CUPS_SEVEN', name: '聖杯七' },
  { id: 'CUPS_EIGHT', name: '聖杯八' },
  { id: 'CUPS_NINE', name: '聖杯九' },
  { id: 'CUPS_TEN', name: '聖杯十' },
  { id: 'CUPS_PAGE', name: '聖杯侍者' },
  { id: 'CUPS_KNIGHT', name: '聖杯騎士' },
  { id: 'CUPS_QUEEN', name: '聖杯皇后' },
  { id: 'CUPS_KING', name: '聖杯國王' },

  { id: 'SWORDS_ACE', name: '寶劍王牌' },
  { id: 'SWORDS_TWO', name: '寶劍二' },
  { id: 'SWORDS_THREE', name: '寶劍三' },
  { id: 'SWORDS_FOUR', name: '寶劍四' },
  { id: 'SWORDS_FIVE', name: '寶劍五' },
  { id: 'SWORDS_SIX', name: '寶劍六' },
  { id: 'SWORDS_SEVEN', name: '寶劍七' },
  { id: 'SWORDS_EIGHT', name: '寶劍八' },
  { id: 'SWORDS_NINE', name: '寶劍九' },
  { id: 'SWORDS_TEN', name: '寶劍十' },
  { id: 'SWORDS_PAGE', name: '寶劍侍者' },
  { id: 'SWORDS_KNIGHT', name: '寶劍騎士' },
  { id: 'SWORDS_QUEEN', name: '寶劍皇后' },
  { id: 'SWORDS_KING', name: '寶劍國王' },

  { id: 'PENTACLES_ACE', name: '錢幣王牌' },
  { id: 'PENTACLES_TWO', name: '錢幣二' },
  { id: 'PENTACLES_THREE', name: '錢幣三' },
  { id: 'PENTACLES_FOUR', name: '錢幣四' },
  { id: 'PENTACLES_FIVE', name: '錢幣五' },
  { id: 'PENTACLES_SIX', name: '錢幣六' },
  { id: 'PENTACLES_SEVEN', name: '錢幣七' },
  { id: 'PENTACLES_EIGHT', name: '錢幣八' },
  { id: 'PENTACLES_NINE', name: '錢幣九' },
  { id: 'PENTACLES_TEN', name: '錢幣十' },
  { id: 'PENTACLES_PAGE', name: '錢幣侍者' },
  { id: 'PENTACLES_KNIGHT', name: '錢幣騎士' },
  { id: 'PENTACLES_QUEEN', name: '錢幣皇后' },
  { id: 'PENTACLES_KING', name: '錢幣國王' },
];

export const TAROT_SPREAD_LIST = [
  {
    id: 'SINGLE',
    name: '單張牌',
    description: '抽取一張牌，獲得簡單的指引。',
    meaning: ['現況'],
    isAiSupport: true,
  },
  {
    id: 'LINEAR',
    name: '時間之流',
    description: '抽取三張牌，代表過去、現在、未來，適合快速知道趨勢。',
    meaning: ['過去', '現在', '未來'],
    isAiSupport: true,
  },
  {
    id: 'CROSS',
    name: '大十字牌陣',
    description:
      '抽取五張牌，時間之流進階版，加上兩張代表理想與隱憂的牌，協助趨吉避凶。',
    meaning: ['理想', '隱憂', '過去', '現在', '未來'],
    isAiSupport: false,
  },
  {
    id: 'FOUR_ELEMENT',
    name: '四元素牌陣',
    description:
      '抽取四張牌，代表大方向、務實面、規劃面、感情面，適合分析現況、結果。',
    meaning: ['行為大方向', '財物務實', '思考計畫', '感情'],
    isAiSupport: false,
  },
  {
    id: 'HEXAGRAM',
    name: '六芒星牌陣',
    description: '抽取六張牌，環境對未來的影響，適合分析未來規劃。',
    meaning: ['過去', '現在', '未來', '原因', '環境', '對策'],
    isAiSupport: false,
  },
  {
    id: 'CUP',
    name: '杯型陣',
    description: '抽取七張牌，適合有標準答案的問題。',
    meaning: ['過去', '現況', '未來', '答案', '環境', '恐懼希望', '結果'],
    isAiSupport: false,
  },
];
