ALTER TABLE altarf.reader ADD COLUMN available BOOLEAN NOT NULL DEFAULT TRUE;
ALTER TABLE altarf.reader ADD COLUMN cost DOUBLE NOT NULL DEFAULT 0;
ALTER TABLE altarf.reader ADD COLUMN fee DOUBLE NOT NULL DEFAULT 0;
ALTER TABLE altarf.reader DROP COLUMN cost_per_reading;