INSERT INTO public.tarot_card (id,"name") VALUES ('MAJOR_O_THE_FOOL','愚者');
INSERT INTO public.tarot_card (id,"name") VALUES ('MAJOR_I_THE_MAGICIAN','魔術師');
INSERT INTO public.tarot_card (id,"name") VALUES ('MAJOR_II_THE_HIGH_PRIESTESS','女祭司');
INSERT INTO public.tarot_card (id,"name") VALUES ('MAJOR_III_THE_EMPRESS','皇后');
INSERT INTO public.tarot_card (id,"name") VALUES ('MAJOR_IV_THE_EMPEROR','皇帝');
INSERT INTO public.tarot_card (id,"name") VALUES ('MAJOR_V_THE_HIEROPHANT','教皇');
INSERT INTO public.tarot_card (id,"name") VALUES ('MAJOR_VI_THE_LOVERS','戀人');
INSERT INTO public.tarot_card (id,"name") VALUES ('MAJOR_VII_THE_CHARIOT','戰車');
INSERT INTO public.tarot_card (id,"name") VALUES ('MAJOR_VIII_STRENGTH','力量');
INSERT INTO public.tarot_card (id,"name") VALUES ('MAJOR_IX_THE_HERMIT','隱者');
INSERT INTO public.tarot_card (id,"name") VALUES ('MAJOR_X_WHEEL_OF_FORTUNE','命運之輪');
INSERT INTO public.tarot_card (id,"name") VALUES ('MAJOR_XI_JUSTICE','正義');
INSERT INTO public.tarot_card (id,"name") VALUES ('MAJOR_XII_THE_HANGED_MAN','倒吊人');
INSERT INTO public.tarot_card (id,"name") VALUES ('MAJOR_XIII_DEATH','死神');
INSERT INTO public.tarot_card (id,"name") VALUES ('MAJOR_XIV_TEMPERANCE','節制');
INSERT INTO public.tarot_card (id,"name") VALUES ('MAJOR_XV_THE_DEVIL','惡魔');
INSERT INTO public.tarot_card (id,"name") VALUES ('MAJOR_XVI_THE_TOWER','高塔');
INSERT INTO public.tarot_card (id,"name") VALUES ('MAJOR_XVII_THE_STAR','星星');
INSERT INTO public.tarot_card (id,"name") VALUES ('MAJOR_XVIII_THE_MOON','月亮');
INSERT INTO public.tarot_card (id,"name") VALUES ('MAJOR_XIX_THE_SUN','太陽');
INSERT INTO public.tarot_card (id,"name") VALUES ('MAJOR_XX_JUDGEMENT','審判');
INSERT INTO public.tarot_card (id,"name") VALUES ('MAJOR_XXI_THE_WORLD','世界');

INSERT INTO public.tarot_card (id,"name") VALUES ('WANDS_ACE','權杖王牌');
INSERT INTO public.tarot_card (id, "name") VALUES ('WANDS_TWO', '權杖二');
INSERT INTO public.tarot_card (id, "name") VALUES ('WANDS_THREE', '權杖三');
INSERT INTO public.tarot_card (id, "name") VALUES ('WANDS_FOUR', '權杖四');
INSERT INTO public.tarot_card (id, "name") VALUES ('WANDS_FIVE', '權杖五');
INSERT INTO public.tarot_card (id, "name") VALUES ('WANDS_SIX', '權杖六');
INSERT INTO public.tarot_card (id, "name") VALUES ('WANDS_SEVEN', '權杖七');
INSERT INTO public.tarot_card (id, "name") VALUES ('WANDS_EIGHT', '權杖八');
INSERT INTO public.tarot_card (id, "name") VALUES ('WANDS_NINE', '權杖九');
INSERT INTO public.tarot_card (id, "name") VALUES ('WANDS_TEN', '權杖十');
INSERT INTO public.tarot_card (id, "name") VALUES ('WANDS_PAGE', '權杖侍者');
INSERT INTO public.tarot_card (id, "name") VALUES ('WANDS_KNIGHT', '權杖騎士');
INSERT INTO public.tarot_card (id, "name") VALUES ('WANDS_QUEEN', '權杖皇后');
INSERT INTO public.tarot_card (id, "name") VALUES ('WANDS_KING', '權杖國王');

INSERT INTO public.tarot_card (id, "name") VALUES ('CUPS_ACE', '聖杯王牌');
INSERT INTO public.tarot_card (id, "name") VALUES ('CUPS_TWO', '聖杯二');
INSERT INTO public.tarot_card (id, "name") VALUES ('CUPS_THREE', '聖杯三');
INSERT INTO public.tarot_card (id, "name") VALUES ('CUPS_FOUR', '聖杯四');
INSERT INTO public.tarot_card (id, "name") VALUES ('CUPS_FIVE', '聖杯五');
INSERT INTO public.tarot_card (id, "name") VALUES ('CUPS_SIX', '聖杯六');
INSERT INTO public.tarot_card (id, "name") VALUES ('CUPS_SEVEN', '聖杯七');
INSERT INTO public.tarot_card (id, "name") VALUES ('CUPS_EIGHT', '聖杯八');
INSERT INTO public.tarot_card (id, "name") VALUES ('CUPS_NINE', '聖杯九');
INSERT INTO public.tarot_card (id, "name") VALUES ('CUPS_TEN', '聖杯十');
INSERT INTO public.tarot_card (id, "name") VALUES ('CUPS_PAGE', '聖杯侍者');
INSERT INTO public.tarot_card (id, "name") VALUES ('CUPS_KNIGHT', '聖杯騎士');
INSERT INTO public.tarot_card (id, "name") VALUES ('CUPS_QUEEN', '聖杯皇后');
INSERT INTO public.tarot_card (id, "name") VALUES ('CUPS_KING', '聖杯國王');

INSERT INTO public.tarot_card (id, "name") VALUES ('SWORDS_ACE', '寶劍王牌');
INSERT INTO public.tarot_card (id, "name") VALUES ('SWORDS_TWO', '寶劍二');
INSERT INTO public.tarot_card (id, "name") VALUES ('SWORDS_THREE', '寶劍三');
INSERT INTO public.tarot_card (id, "name") VALUES ('SWORDS_FOUR', '寶劍四');
INSERT INTO public.tarot_card (id, "name") VALUES ('SWORDS_FIVE', '寶劍五');
INSERT INTO public.tarot_card (id, "name") VALUES ('SWORDS_SIX', '寶劍六');
INSERT INTO public.tarot_card (id, "name") VALUES ('SWORDS_SEVEN', '寶劍七');
INSERT INTO public.tarot_card (id, "name") VALUES ('SWORDS_EIGHT', '寶劍八');
INSERT INTO public.tarot_card (id, "name") VALUES ('SWORDS_NINE', '寶劍九');
INSERT INTO public.tarot_card (id, "name") VALUES ('SWORDS_TEN', '寶劍十');
INSERT INTO public.tarot_card (id, "name") VALUES ('SWORDS_PAGE', '寶劍侍者');
INSERT INTO public.tarot_card (id, "name") VALUES ('SWORDS_KNIGHT', '寶劍騎士');
INSERT INTO public.tarot_card (id, "name") VALUES ('SWORDS_QUEEN', '寶劍皇后');
INSERT INTO public.tarot_card (id, "name") VALUES ('SWORDS_KING', '寶劍國王');

INSERT INTO public.tarot_card (id, "name") VALUES ('PENTACLES_ACE', '錢幣王牌');
INSERT INTO public.tarot_card (id, "name") VALUES ('PENTACLES_TWO', '錢幣二');
INSERT INTO public.tarot_card (id, "name") VALUES ('PENTACLES_THREE', '錢幣三');
INSERT INTO public.tarot_card (id, "name") VALUES ('PENTACLES_FOUR', '錢幣四');
INSERT INTO public.tarot_card (id, "name") VALUES ('PENTACLES_FIVE', '錢幣五');
INSERT INTO public.tarot_card (id, "name") VALUES ('PENTACLES_SIX', '錢幣六');
INSERT INTO public.tarot_card (id, "name") VALUES ('PENTACLES_SEVEN', '錢幣七');
INSERT INTO public.tarot_card (id, "name") VALUES ('PENTACLES_EIGHT', '錢幣八');
INSERT INTO public.tarot_card (id, "name") VALUES ('PENTACLES_NINE', '錢幣九');
INSERT INTO public.tarot_card (id, "name") VALUES ('PENTACLES_TEN', '錢幣十');
INSERT INTO public.tarot_card (id, "name") VALUES ('PENTACLES_PAGE', '錢幣侍者');
INSERT INTO public.tarot_card (id, "name") VALUES ('PENTACLES_KNIGHT', '錢幣騎士');
INSERT INTO public.tarot_card (id, "name") VALUES ('PENTACLES_QUEEN', '錢幣皇后');
INSERT INTO public.tarot_card (id, "name") VALUES ('PENTACLES_KING', '錢幣國王');
